config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:create, :show, :edit, :index, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  # has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy

  # def get_image
  #   unless image.attached?
  #     file_path = Rails.root.join('app/assets/images/no_image.jpg')
  #     image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  #   end
  #   image
  # end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {  maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "You have created book successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @books = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
      book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # @books = Book.all
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # @books = Book.all
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= render 'layouts/errors', obj: @book %>

<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: "form-control book_body", id: "book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% books.each do |book| %>
    <tr id="book_<%= book.id %>">
      <td>
        <%= link_to user_path(book.user.id) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
      </td>
      <td>
        <%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %>
      </td>
      <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-log-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <%= render 'layouts/errors', obj: @book %>

      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, id:"book_title", class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, id:"book_body", class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
     <% end %>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user, book: @book %>
      <h2class="col-md-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'index', books: @books, user: @user %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2>New book</h2>
      <%= render 'form', book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <tr id="book_<%= book.id %>">
          <td>
          <%= link_to user_path(@book.user.id) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %><br>
            <%= @book.user.name %>
          <% end %>
          </td>
          <td>
          <%= link_to book_path(@book.id) do %>
            <%= @book.title %>
          <% end %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
          <td>
          <% if @book.user == current_user %>
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
            <%= link_to "Destroy", book_path(@book), method: :delete,"data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
          <% end %>
          </td>
        </tr>
      </table>

    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <p>
      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
      <%= book.favorites.count %>
    </p>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <P>
      <i class="far fa-heart" aria-hidden="true"></i>
      <%= book.favorites.count %>
    </P>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#book_<%= book.id %> .favorite-btn').html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$('#book_<%= book.id %> .favorite-btn').html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/homes/about.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
      <!--flash-->
<div>
  <%= flash[:notice] %>
</div>
      <!--flash-->

<p id="notice"></p>
<div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>
      welcome to
      <i class="fas fa-book"></i><strong>Bookers</strong>!!
    </h1>
    <p>
      In
      <i class="fas fa-book"></i><strong>Bookers</strong>
      ,
    </p>
    <p>
      you can share and exchange your opinions, inpressions, and emotions
    <p>about various books!</p>
    </p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
      </div>
      <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up"  %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <%= link_to root_path, class: "navbar-brand" do %>
          <span>Bookers</span>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>
              Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i>
              Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fas fa-book-open"></i>
              Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i>
              Log out
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>
              Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: "nav-link text-light" do %>
              <i class="fas fa-link"></i>
              About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i>
              Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i>
              Log in
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
      <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% users.each do |user| %>
    <tr>
      <td>
        <%= link_to user_path(user.id) do %>
        <%= image_tag user.get_profile_image(100,100) %>
        <% end %>
      </td>
      <td><%= user.name %></td>
      <td><%= render 'relationships/btn', user: user %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class="table">
  <tr><%= image_tag user.get_profile_image(100, 100) %></tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>followings</th>
    <td><%= link_to user.followings.count, user_followings_path(user) %></td>
  </tr>
  <tr>
    <th>followed</th>
    <td><%= link_to user.followers.count, user_followers_path(user) %></td>
  </tr>
</table>

<div class="row">
  <% if current_user != user %>
    <td><%= render 'relationships/btn', user: user %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<p id="notice"></p>

<!--エラーメッセージ-->

<div id="error_explanation">
  <% if @user.errors.any? %>
  <h3>
    <%= @user.errors.count %>  errors prohibited this obj from being saved:
  </h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<!--エラーメッセージ-->

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-log-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, id:"user_name", class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction,  id:"user_introduction", class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2>New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2>New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <div  class="favorite-btn"><%= render 'books/index', books: @books %></div>
    </div>
  </div>
</div>